timeout: '3600s'

steps:
  - id: 'pull-tagger'
    name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/cloud-builders/tagger:latest']

  - id: 'pull-latest'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'pull'
      - 'gcr.io/$PROJECT_ID/apps/term-check:latest'

  - id: 'term-check-build'
    name: 'gcr.io/cloud-builders/docker'
    waitFor: ['pull-tagger', 'pull-latest']
    args:
      - 'build'
      - '--cache-from=grc.io/$PROJECT_ID/apps/term-check:latest'
      - '--tag=gcr.io/$PROJECT_ID/apps/term-check'
      - '--file=Dockerfile'
      - '.'

  - id: 'tag-image'
    name: 'gcr.io/$PROJECT_ID/cloud-builders/tagger'
    waitFor: ['term-check-build']
    env:
      - SOURCE_IMAGE=gcr.io/$PROJECT_ID/apps/term-check
      - IMAGE_NAME=gcr.io/$PROJECT_ID/apps/term-check
      - BRANCH_NAME=$BRANCH_NAME
      - TAG_NAME=$TAG_NAME
      - TAG_NON_MASTER_BRANCH=1

images:
  - 'gcr.io/$PROJECT_ID/apps/term-check'